### ISSUE TITLE
Add CalcMod?

### ISSUE THREAD

**Issue by shadeydo** [LordImmaculate/FabulouslyEnhanced#1]
calcmod is a simple calculator in the chat with extra features to make life easier! good QoL fit for Fabulously enhanced! heres a link to the modrinth page: [https://modrinth.com/mod/calcmod](https://modrinth.com/mod/calcmod)

**Comment by LordImmaculate** [comment]
Yeah i did a total revision of the project, ill add the mod and i'll publish it
I didn't think anyone would use my modpack, thanks for posting this!

**Comment by LordImmaculate** [comment]
Btw why did u ask to add a mod on multiple projects even though it isn't ur mod?

**Comment by shadeydo** [comment]
i am 1/2 of the devs

**Comment by LordImmaculate** [comment]
Oh okay thats cool!
